### ISSUE TITLE
Download to Stream

### ISSUE THREAD

**Issue by egbertn** [carbon/Amazon#15]
Hi There, good job!

I would like to propose the following small feature. I need it to start streaming asap without waiting until a file has been copied locally.

Thanks!

 public static async Task DownloadAsync(
       this S3Bucket bucket,
       string objectKey,
       Stream destinationStream,
       S3DownloadOptions? options = null,
       CancellationToken cancellationToken = default)
    {
Nice if we get range-request pass-through as well because that is what a streaming support needs.
Let me know if you have time for this. Otherwise I will make a PR.
...

**Comment by iamcarbon** [comment]
@[egbertn](https://github.com/egbertn)

TheS3Bucket::GetAsync(key) function returns a non-buffered stream by default. 

The DownloadAsync function is special in that it can open multiple-concurrent range requests on different threads and write to a file concurrently to max out a network connection / disk throughput. 

Let me know if there's any feature you're looking for here.

**Comment by egbertn** [comment]
@iamcarbon  looks perfect. Thanks!
